repos:
- repo: https://github.com/commitizen-tools/commitizen
  rev: v3.24.0
  hooks:
    - id: commitizen

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: "v1.10.0"
  hooks:
    - id: mypy
      entry: "hatch run types:check"
      stages: [pre-commit]

- repo: local
  hooks:
    - id: format
      name: format
      entry: hatch fmt --check
      language: python
      types: [python]
      pass_filenames: false
      verbose: true
