name: Create pre-release

on:
  workflow_dispatch

concurrency:
  group: build-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"
  REVISION: ""

jobs:
  version_bump:
    name: "Version bump to release candidate version"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: "${{ github.token }}"

      - name: Create bump and changelog
        id: cz
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ github.token }}
          changelog: false
          prerelease: "rc"


      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.cz.outputs.version }}
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
